apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment.name }}
    type: frontend
  name: fe-deploy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: frontend-vimalmenon
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend-vimalmenon
        type: frontend
    spec:
      containers:
        - image: {{ .Values.deployment.image }}:{{ .Values.deployment.version }}
          name: {{ .Values.deployment.name}}-pod

