apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.name }}
    app.kubernetes.io/managed-by: Helm
    type: frontend
  name: fe-deploy
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    app: {{ .Values.deployment.name }}
  type: NodePort
