name: Check Code Quality

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: 21.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{env.NODE_VERSION}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
    - name: Run lint
      run: npm run eslint
    - name: Run Type checking
      run: npm run tsc
    - name: Run test
      run: npm run test
